# routes.yaml
home:
    path:     /home
    defaults: { controller: 'home' }
employees:
    path:     /employees
    defaults: { controller: 'employeesList' }
employees_placeholder:
    path:     /employees/{id}
    defaults: { controller: 'employee' }
    requirements:
        id: '[0-9]+'
employees_create:
    path:     /employees/create
    defaults: { controller: 'create' }
employees_delete: 
    path:     /employeesdelete/{id}
    defaults: { controller: 'delete' }
    requirements:
        id: '[0-9]+'